#!/usr/bin/env node
/**
 * Static page generator for droneaid.pl. Zero dependencies, Node 18+.
 *
 *   src/templates/*.html   page templates ({{key}} placeholders, {{> partial}} includes)
 *   src/partials/*.html    fragments shared between templates (head, footer)
 *   src/i18n/<lang>.json   translated UI strings; "meta" holds the per-language <head> data
 *   src/site.json          language-independent data: site URL, language list, stats
 *   src/css, src/js        stylesheet and ES modules, copied to the output as-is
 *   src/static/            files copied to the output root as-is (robots.txt, sitemap.xml)
 *   dist/                  OUTPUT. Wiped and rebuilt on every run, git-ignored; the host
 *                          runs "npm run build" and publishes this folder.
 *
 * Placeholder syntax
 *   {{key}}        insert the value as-is (values may contain HTML such as <br> and <em>)
 *   {{key|attr}}   HTML-escape the value, for attributes and <title>
 *   {{key|json}}   emit a JSON string literal (quotes included), for JSON-LD
 *   {{a.b.c}}      dotted paths, e.g. {{site.stats.people}} or {{meta.title}}
 *   {{> name}}     include src/partials/name.html
 *
 * The build fails on a missing key so a page can never ship with a hole in it,
 * and warns about keys that differ between languages or are no longer used.
 */
import { cpSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'src');
const OUT = join(ROOT, 'dist');

const read = (path) => readFileSync(path, 'utf8');
const readJson = (path) => JSON.parse(read(path));

const site = readJson(join(SRC, 'site.json'));
const i18n = Object.fromEntries(
  Object.keys(site.languages).map((lang) => [lang, readJson(join(SRC, 'i18n', `${lang}.json`))]),
);
const partials = Object.fromEntries(
  readdirSync(join(SRC, 'partials')).map((file) => [file.replace(/\.html$/, ''), read(join(SRC, 'partials', file))]),
);

/* ---- static assets ------------------------------------------------------- */

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });
cpSync(join(SRC, 'css'), join(OUT, 'css'), { recursive: true });
cpSync(join(SRC, 'js'), join(OUT, 'js'), { recursive: true });
cpSync(join(SRC, 'static'), OUT, { recursive: true });
console.log('✓ dist/css, dist/js, static files');

/* ---- pages --------------------------------------------------------------- */

const filters = {
  attr: (value) =>
    String(value).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;'),
  json: (value) => JSON.stringify(String(value)),
};

const lookup = (ctx, path) => path.split('.').reduce((obj, key) => (obj == null ? undefined : obj[key]), ctx);

function render(template, ctx, used, where) {
  return template
    .replace(/\{\{>\s*([\w-]+)\s*\}\}/g, (_, name) => {
      if (!partials[name]) throw new Error(`${where}: unknown partial "${name}"`);
      return render(partials[name], ctx, used, `partials/${name}.html`);
    })
    .replace(/\{\{\s*([\w.-]+)\s*(?:\|\s*(\w+)\s*)?\}\}/g, (_, path, filter) => {
      const value = lookup(ctx, path);
      if (value === undefined) throw new Error(`${where}: no value for {{${path}}}`);
      if (filter && !filters[filter]) throw new Error(`${where}: unknown filter "${filter}"`);
      used.add(path);
      return filter ? filters[filter](value) : String(value);
    });
}

/** Pages to generate. The landing page is rendered once per language; privacy is English only. */
const pages = [
  ...Object.entries(site.languages).map(([lang, l]) => ({
    template: 'index', lang, out: `${l.path}index.html`, vars: { navBase: '' },
  })),
  { template: 'privacy', lang: 'en', out: 'privacy.html', vars: { navBase: 'index.html' } },
];

const usedByTemplate = {};

for (const page of pages) {
  const l = site.languages[page.lang];
  const base = l.path ? '../' : './'; // relative prefix back to the site root

  const ctx = {
    ...i18n[page.lang],
    site,
    lang: page.lang,
    locale: l.locale,
    base,
    url: `${site.url}/${l.path}`,
    ogAlternates: Object.values(site.languages)
      .filter((other) => other !== l)
      .map((other) => `<meta property="og:locale:alternate" content="${other.locale}"/>`)
      .join('\n  '),
    langBtn: Object.fromEntries(
      Object.entries(site.languages).map(([code, other]) => [code, {
        href: base + other.path,
        cls: code === page.lang ? 'btn-primary' : 'btn-ghost',
        current: code === page.lang ? ' aria-current="page"' : '',
      }]),
    ),
    ...page.vars,
  };

  const used = (usedByTemplate[page.template] ??= new Set());
  const template = read(join(SRC, 'templates', `${page.template}.html`));
  const notice = `<!-- GENERATED by scripts/build.mjs from src/templates/${page.template}.html + src/i18n/${page.lang}.json. Edit the source and run "npm run build"; do not edit this file. -->`;
  const html = render(template, ctx, used, `templates/${page.template}.html`)
    .replace(/^<!DOCTYPE html>\r?\n/i, `<!DOCTYPE html>\n${notice}\n`);

  const outPath = join(OUT, page.out);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, html);
  console.log(`✓ dist/${page.out}`);
}

/* ---- consistency checks -------------------------------------------------- */

const flatten = (obj, prefix = '') =>
  Object.entries(obj).flatMap(([k, v]) =>
    v && typeof v === 'object' ? flatten(v, `${prefix}${k}.`) : [`${prefix}${k}`]);

const warn = (msg) => { process.exitCode = 0; console.warn(`⚠ ${msg}`); };
const usedKeys = new Set(Object.values(usedByTemplate).flatMap((set) => [...set]));
const reference = flatten(i18n.en);

for (const [lang, strings] of Object.entries(i18n)) {
  const keys = flatten(strings);
  reference.filter((k) => !keys.includes(k)).forEach((k) => warn(`${lang}.json is missing "${k}" (present in en.json)`));
  keys.filter((k) => !reference.includes(k)).forEach((k) => warn(`${lang}.json has "${k}", which en.json does not`));
}
reference.filter((k) => !usedKeys.has(k)).forEach((k) => warn(`"${k}" is defined in en.json but used by no template`));
